spring:
  application:
    name: PersonalBlog
  datasource:
    url: jdbc:mysql://localhost:3306/personalblog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
server:
  port: 8080
mybatis:
  mapper-locations: classpath:com/liuyan/personalblog/Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: blogavatar
    region: cn-beijing

langchain4j:
  open-ai:
#    streaming-chat-model:
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
#      api-key: sk-682ccd0c404e46e786601ae692d4d040
#      model-name: qwen-plus
#      log-requests: true
#      log-responses: true
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-682ccd0c404e46e786601ae692d4d040
      model-name: qwen-plus
      log-requests: true
      log-responses: true
